# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: carlosperate/download-file-action@v2
        name: download-coverage
        with:
          file-url: 'https://onetest-opensource-oss.oss-us-west-1.aliyuncs.com/onetest/coverage/4cd5cafb-3a65-4e95-800f-3907a356c0b0/coverageReport.zip'
          file-name: 'coverageReport.zip'
      - run: |
          unzip coverageReport.zip
          ls
          mkdir xml-report
          cp -r *.xml xml-report/
          pwd
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
            paths: ./mst-automation-report.xml,./mst-gateway-report.xml,./mst-inspect-report.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 1
            min-coverage-changed-files: 1
