# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: carlosperate/download-file-action@v2
        name: download-coverage
        with:
          file-url: 'https://onetest-opensource-oss.oss-us-west-1.aliyuncs.com/onetest/coverage/5b146481-5ad4-45b9-858e-6179bfd1255c/coverageReport.zip'
          file-name: 'coverageReport.zip'
      - run: |
          unzip coverageReport.zip
          ls
          mkdir xml-report
          cp -r *.xml xml-report/
          pwd
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
            paths: ./openmessaging-report.xml,./controller-report.xml,./namesrv-report.xml,./broker-report.xml,./client-report.xml,./proxy-report.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            update-comment: RocketMQ Coverage Report
            title: Coverage
            min-coverage-overall: 1
            min-coverage-changed-files: 1
