# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: carlosperate/download-file-action@v2
        name: download-coverage
        with:
          file-url: 'https://onetest-opensource-oss.oss-us-west-1.aliyuncs.com/onetest/coverage/4cd5cafb-3a65-4e95-800f-3907a356c0b0/coverageReport.zip'
          file-name: 'coverageReport.zip'
          location: './coverage'
      - name: unzip
      - run: |
          unzip coverageReport.zip
          ls
      - name: Print the file path (new-folder-to-be-created/new_filename.tar.gz)
          run: echo "The file was downloaded to ${{ steps.download-coverage.outputs.file-path }}"


      - uses: codecov/codecov-action@v3
        name: upload-to-codecov
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          #files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          directory: ./coverage/
          path_to_write_report: ./coverage/codecov_report.txt
