# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: carlosperate/download-file-action@v2
        name: download-coverage
        with:
          file-url: 'https://onetest-opensource-oss.oss-us-west-1.aliyuncs.com/onetest/coverage/coverage.xml'
          file-name: 'coverage.xml'
      - run: |
          ls
          pwd

      - uses: codecov/codecov-action@v3
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          #directory: ./coverage/
          path_to_write_report: ./coverage/codecov_report.txt

